### ISSUE TITLE
database

### ISSUE THREAD

**Issue by ANKIT143-cmd** [Jincy17/Fantasy-Cricket-Game#1]
The database.py file is not in the source code. It only has database.db file.

**Comment by jincy-p-janardhanan** [comment]
Well, you've got your concepts wrong. Database.py file is not required since database is not a python file. 
SQLite database files usually have the .db extension which stands for database. You may open the cricket.db file using SQLite.
If you haven't got any more queries, I may close this issue.

**Comment by ANKIT143-cmd** [comment]
In the project there is only one .db for database. But your project
doesn't have the file that I am sending you as attachment.

**Comment by ANKIT143-cmd** [comment]
And also do you have the Data flow diagram and Project report?? Looking
forward to hear from you.

**Comment by jincy-p-janardhanan** [comment]
Hi,
Sorry, what's the missing file you're mentioning? I've uploaded the entire folder I've used for this project and it will work fine if you've cloned (or downloaded and unzipped) this repository and run the Game.py file using any python interpreter. If you change the filenames, you may have to make relevant changes in all associated files (i.e in the import statements). Also, make sure your environment variables are set to support the execution of python files. If you encounter any problems accessing the database, make sure you have the sqlite3 package.
Please explain any errors, if any, that you get while executing the Game.py file along with the error codes and descriptions so that I may be able to help you.
P.S: I didn't receive any attachment.

**Comment by jincy-p-janardhanan** [comment]
I've not prepared any DFDs for this project since Internshala doesn't require it. I have the synopsis of the project but I do not wish to share it. 

The development of problem solutions may require good programming knowledge and perhaps, some inspiration. So, it's helpful to open source development code. However, project reports and synopses are not technical stuff and should be prepared individually.

If you need any guidance to prepare a synopsis for your Internshala project, I may offer a quick outline of what I've included in the synopsis:
- A cover page
- Abstract
- Problem Statement _(in brief)_
- Development of Solution - _Here, I've included the various steps taken (in order) to develop the solution._
- User Interfaces - _Here I mentioned all the user interfaces developed for the project and briefly detailed various components of the UI as bullet points._
- Database Design - _Here I mentioned all the tables used in the project and briefly explained their purposes._
- Python Program and Modules - _In this section, I briefed about the different modules of the project. (It would be better if you could document all the functions defined in each module.)_
- Application Screenshots - _Here, I've included screenshots of all the activities that can be performed with the application (in order). E.g. Opening screen, creating a new team, etc._
- References
- Acknowledgement

Internshala doesn't specify any specific format for the synopsis, so you may as well follow any format you prefer. Standard or commercial project reports may follow a very different and sophisticated style, which, I think, is not required for this project and you can go for a report with a simple structure.

**Comment by ANKIT143-cmd** [comment]
Thanks for the information.
